version: "2"
services:
  subscription-bff:
    container_name: subscription-backend-for-fronted
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: adidas-backend-for-frontend-mcsv:latest
    volumes:
      - ./src/main/resources/certs/:/certs/
    ports:
      - "8081:8081"
    environment:
      - TZ=America/Sao_Paulo
